<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Npgsql">
      <HintPath>C:\Users\pontu\.nuget\packages\npgsql\9.0.3\lib\net8.0\Npgsql.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="QueryUsers.cs" />
  </ItemGroup>
</Project>
