using System.ComponentModel.DataAnnotations;

namespace sidequest.backend.Models;

public static class GlunoTurnRequestStatuses
{
    /// A turn is running right now.
    public const string InFlight = "in_flight";
    /// It finished and produced an assistant message.
    public const string Completed = "completed";
    /// It failed; the code says how.
    public const string Failed = "failed";
    /// The user stopped it.
    public const string Cancelled = "cancelled";
}

/// <summary>
/// One user turn, keyed by a client-generated idempotency id.
///
/// WHY THIS EXISTS. A chat send is the least reliable request in the app: it
/// takes seconds, people double-tap, phones drop connections mid-flight and
/// retry. Without this, a retry produces a second user bubble, a second model
/// turn (paid for), a second answer, and — worst of all — a second proposal,
/// so the user can apply the same day plan twice and get every Activity
/// duplicated.
///
/// The idempotency key is generated by the CLIENT, because only the client
/// knows that two requests are the same intent rather than two identical
/// questions asked deliberately. Someone typing "what's missing?" twice on
/// purpose is entitled to two answers.
///
/// SCOPE. User plus conversation. A key is meaningless outside the conversation
/// it belongs to, and scoping it to the user means one person's key can never
/// return another person's answer.
/// </summary>
public class GlunoTurnRequest
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The client's key. Opaque to the backend — validated for shape and
    /// length, never parsed.
    /// </summary>
    [Required]
    [MaxLength(64)]
    public string IdempotencyKey { get; set; } = string.Empty;

    public Guid UserId { get; set; }
    public Guid ConversationId { get; set; }

    /// <see cref="GlunoTurnRequestStatuses"/>.
    [Required]
    [MaxLength(20)]
    public string Status { get; set; } = GlunoTurnRequestStatuses.InFlight;

    /// <summary>
    /// The assistant message this turn produced, so a replay returns the
    /// original answer rather than generating a second one.
    /// </summary>
    public Guid? AssistantMessageId { get; set; }

    /// A stable failure code when the turn failed. Never a provider message.
    [MaxLength(40)]
    public string? FailureCode { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
